### ISSUE TITLE
Support Tailwind CSS v1.0

### ISSUE THREAD

**Issue by buismaarten** [adevade/color-scheme-generator#1]
Maybe an idea to update the tool for Tailwind CSS version 1.0?

**Comment by adevade** [comment]
It should work with 1.0 as well. 
If you have encountered a problem, please respond and give some more details and I'll be happy to (try to) fix it :smile:

**Comment by buismaarten** [comment]
See the differences between https://v0.tailwindcss.com/docs/background-color and https://tailwindcss.com/docs/background-color, the use different color classes across the whole library.

**Comment by adevade** [comment]
You can use any name you want for color names, in both v0 and v1, so you can rename the names you get from this generator if you want to match them to v1 style. 

The generated colors from this tool is meant to replace the default color palette.
